# Generated by Django 5.1.3 on 2024-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateAtDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=6)),
                ('exchange_rate', models.FloatField()),
                ('date', models.DateTimeField(verbose_name='date registered')),
            ],
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
